site_name: voltage!studios docs
theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch between light and dark mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share